version: "3"

networks:
  net:
    driver: bridge

services:
  nginx:
    image: nginx:1.18-alpine
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net
    depends_on:
      - api

  api:
    image: roberto0arruda/php-fpm
    volumes:
      - ./:/var/www
    expose:
      - 9000
    networks:
      - net
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    tty: true
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - net
